### ISSUE TITLE
Crashing after running hurricane module.

### ISSUE THREAD

**Issue by 0xaud** [j3ssie/IPOsint#2]
Hey,

App is crashing as soon as hurricane module comes into action.
Logs 

`Traceback (most recent call last):
  File "ip-osint.py", line 141, in <module>
    main()
  File "ip-osint.py", line 137, in main
    parsing_argument(args)
  File "ip-osint.py", line 87, in parsing_argument
    single_target()
  File "ip-osint.py", line 96, in single_target
    hurricane.Hurricane(options)
  File "/root/Desktop/pentest/IPOsint/modules/hurricane.py", line 14, in __init__
    self.initial()
  File "/root/Desktop/pentest/IPOsint/modules/hurricane.py", line 17, in initial
    real_data = self.get_real_content()
  File "/root/Desktop/pentest/IPOsint/modules/hurricane.py", line 41, in get_real_content
    response = core.open_with_chrome(url)
  File "/root/Desktop/pentest/IPOsint/modules/core.py", line 92, in open_with_chrome
    browser = webdriver.Chrome(executable_path=chromedriver, options=options)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/common/service.py", line 76, in start
    stdin=PIPE)
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)`

**Comment by p3t3r67x0** [comment]
Hi I like your work! I tried your script but unfortunately I got an error while scraping `Hurricane`.

```
Traceback (most recent call last):
  File "./ip-osint.py", line 141, in <module>
    main()
  File "./ip-osint.py", line 137, in main
    parsing_argument(args)
  File "./ip-osint.py", line 87, in parsing_argument
    single_target()
  File "./ip-osint.py", line 96, in single_target
    hurricane.Hurricane(options)
  File "/home/<username>/git/IPOsint/modules/hurricane.py", line 14, in __init__
    self.initial()
  File "/home/<username>/git/IPOsint/modules/hurricane.py", line 17, in initial
    real_data = self.get_real_content()
  File "/home/<username>/git/IPOsint/modules/hurricane.py", line 41, in get_real_content
    response = core.open_with_chrome(url)
  File "/home/<username>/git/IPOsint/modules/core.py", line 92, in open_with_chrome
    browser = webdriver.Chrome(executable_path=chromedriver, options=options)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/common/service.py", line 76, in start
    stdin=PIPE)
  File "/usr/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/home/<username>/git/IPOsint/modules/chromedriver'
```


**Enviroment**

`uname -r`

```
4.15.0-44-generic
```

`lsb_release -a`

```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic
```

**Comment by j3ssie** [comment]
Confirm that this is a bug after testing on my Kali Linux, but somehow this not an issue(maybe cert stuff) on my Mac.
Will be investigate more about it.
Thanks for feedback.

**Comment by j3ssie** [comment]
it should be fixed now

**Comment by 0xaud** [comment]
Maybe not @j3ssie 

` python3 ip-osint.py -t hackerone.com

          -----------------------------
        < You didn't say the MAGIC WORD >
          ----------------------------- 
                 \   ^__^
                  \  (oo)\_______
                     (__)\       )\/
                        \||----w |    
                         ||     ||    Contact: @j3ssiejjj

--~~~=:>[ Starting scraping IP from Whois ]>
[*] 104.16.99.52
[*] 104.16.99.52
[*] 104.16.99.52
[*] 104.16.99.52
[*] 104.16.99.52
[*] 104.16.99.52
[*] 104.16.99.52
--~~~=:>[ Starting scraping IP from Ripe ]>
[*] 127.0.0.1
--~~~=:>[ Starting scraping IP from Arin ]>
--~~~=:>[ Starting scraping IP from Hurricane ]>
[-] Some thing wrong with Hurricane module
--~~~=:>[ Starting scraping IP from Censys ]>
Traceback (most recent call last):
  File "ip-osint.py", line 146, in <module>
    main()
  File "ip-osint.py", line 142, in main
    parsing_argument(args)
  File "ip-osint.py", line 91, in parsing_argument
    single_target()
  File "ip-osint.py", line 101, in single_target
    cencys.Censys(options)
  File "/root/Desktop/pentest/IPOsint/modules/cencys.py", line 16, in __init__
    self.initial()
  File "/root/Desktop/pentest/IPOsint/modules/cencys.py", line 19, in initial
    real_data = self.get_real_content()
  File "/root/Desktop/pentest/IPOsint/modules/cencys.py", line 51, in get_real_content
    response = core.open_with_chrome(url)
  File "/root/Desktop/pentest/IPOsint/modules/core.py", line 93, in open_with_chrome
    browser = webdriver.Chrome(executable_path=chromedriver, options=options)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/common/service.py", line 76, in start
    stdin=PIPE)
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
OSError: [Errno 8] Exec format error
root@bugdiscloseguy:~/Desktop/pentest/`
