### ISSUE TITLE
UnboundLocalError

### ISSUE THREAD

**Issue by eos21** [j3ssie/IPOsint#4]
--~~~=:>[ Starting scraping IP from Hurricane ]>
[-] Some thing wrong with Hurricane module
--~~~=:>[ Starting scraping IP from Censys ]>
Traceback (most recent call last):
  File "./ip-osint.py", line 141, in <module>
    main()
  File "./ip-osint.py", line 137, in main
    parsing_argument(args)
  File "./ip-osint.py", line 87, in parsing_argument
    single_target()
  File "./ip-osint.py", line 97, in single_target
    cencys.Censys(options)
  File "/media/jacky/0BAA3A4E616EBBCD/IPOsint/modules/cencys.py", line 16, in __init__
    self.initial()
  File "/media/jacky/0BAA3A4E616EBBCD/IPOsint/modules/cencys.py", line 19, in initial
    real_data = self.get_real_content()
  File "/media/jacky/0BAA3A4E616EBBCD/IPOsint/modules/cencys.py", line 43, in get_real_content
    cert_fin = self.get_cert_fingerprint(target)
  File "/media/jacky/0BAA3A4E616EBBCD/IPOsint/modules/cencys.py", line 101, in get_cert_fingerprint
    return thumb_sha256
UnboundLocalError: local variable 'thumb_sha256' referenced before assignment

**Comment by eos21** [comment]
Below is my OS info:

No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.5 LTS
Release:	16.04
Codename:	xenial

**Comment by j3ssie** [comment]
This happen when you type a domain that doesn’t have ssl so it can’t the cert fingerprint.
Could you give me your command you ran.

**Comment by j3ssie** [comment]
it should be fixed now
