### ISSUE TITLE
Modules not working & ChromeDriver error

### ISSUE THREAD

**Issue by opabravo** [j3ssie/IPOsint#7]
```
python3 ip-osint.py -t Google

          -----------------------------
        < You didn't say the MAGIC WORD >
          -----------------------------
                 \   ^__^
                  \  (oo)\_______
                     (__)\       )\/
                        \||----w |
                         ||     ||    Contact: @j3ssiejjj

--~~~=:>[ Starting scraping IP from Whois ]>
[*] 172.217.3.164
[*] 172.217.3.164
[*] 172.217.3.164
[*] 172.217.3.164
[*] 172.217.3.164
[*] 172.217.3.164
[*] 172.217.3.164
--~~~=:>[ Starting scraping IP from Ripe ]>
...
[+] Range IP detect
--~~~=:>[ Starting scraping IP from Arin ]>
[-] Some thing wrong with Arin module
--~~~=:>[ Starting scraping IP from Hurricane ]>
[-] Some thing wrong with Hurricane module
--~~~=:>[ Starting scraping IP from Censys ]>
[-] Your target seem doesn't run on SSL
--~~~=:>[ Starting scraping IP from SecurityTrails ]>
Traceback (most recent call last):
  File "ip-osint.py", line 146, in <module>
    main()
  File "ip-osint.py", line 142, in main
    parsing_argument(args)
  File "ip-osint.py", line 91, in parsing_argument
    single_target()
  File "ip-osint.py", line 102, in single_target
    securitytrails.SecurityTrails(options)
  File "/mnt/c/Users/GOD/Desktop/IPOsint/modules/securitytrails.py", line 15, in __init__
    self.initial()
  File "/mnt/c/Users/GOD/Desktop/IPOsint/modules/securitytrails.py", line 18, in initial
    real_data = self.get_real_content()
  File "/mnt/c/Users/GOD/Desktop/IPOsint/modules/securitytrails.py", line 43, in get_real_content
    response = core.open_with_chrome(url)
  File "/mnt/c/Users/GOD/Desktop/IPOsint/modules/core.py", line 93, in open_with_chrome
    browser = webdriver.Chrome(executable_path=chromedriver, options=options)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/common/service.py", line 76, in start
    stdin=PIPE)
  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/mnt/c/Users/GOD/Desktop/IPOsint/modules/chromedriver'
```

**Comment by j3ssie** [comment]
Could you give me some more details like your OS info and directory listing in the modules folder?

**Comment by j3ssie** [comment]
Oops, look like I committed chromedriver for Mac on the repo.
It's should be fix now.
